### PR TITLE
feature: improved UX and performance of group invites

### PR DESCRIPTION
**Pull request by hypeJunction**
I have cherry picked this, so sorry for the noise.

This effectively removes custom autocomplete implementation, but I prefer core inputs for sake of consistency and readability.

invite
invite-friends

### CODE REVIEW

**Comment by Wouter0100** [comment]
Is there any way to get this merged? We'd like to upgrade to Elgg 2.x. This would be an awesome feature.

**Comment by hypeJunction** [comment]
@Wouter0100 I have since built my own plugin for group invites, which you can check out here: https://github.com/hypejunction/Elgg-groups_invite

**Comment by Wouter0100** [comment]
Hmm, didn't see that. Thanks. Awesome.

**Comment by jeabakker** [comment]
i won't be pulling this in. But i did take the majority of the refactoring into the plugin.

reasons:
1. a little bit to much noise :(
2. i can't merge anymore because of all my refactoring
3. there is a reason behind the custom autocomplete (status if the user is already a member, email address validation)

still thanks for all the work, i copied some of it

**Pull request closed without merging**
