### PR TITLE
js: refactors a lot of js into amd

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by Wouter0100** [comment]
Is there any way to get this merged? We'd like to upgrade to Elgg 2.x. This solves some problems.

**Comment by jdalsem** [comment]
@Wouter0100 we are in the process of upgrading our plugins. You can expect group_tools in a few weeks...

**Comment by Wouter0100** [comment]
@jdalsem Awesome!

**Comment by jeabakker** [comment]
thanks for the work!

**Pull request merged**
